GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYyNDQxNjU4OX0.V6ggxqto8ZBfflWNWEgE3-boAEg3wTwRFSG1IH2TrhI

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Ryan"
}