GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYyNDU1MDQ0OSwiZXhwIjoxNjI0NTUwNDY0fQ.WGihh1-zGinyhcpmy3-4gtlNzDTmcLEwlVCmzhJERE0

###
POST http://localhost:3001/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYyNDU1MDIzOX0.95H7-zbnyVvmjm3DKQnEhQS4wRoU6lBrXAp8gXb0z5o"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "Ryan"
}